from webserver import keep_alive
import os
import discord
import datetime
import asyncio
import json
import requests
from discord.ext import commands
from dhooks import Webhook
...

custom_prefixes = {}
#You'd need to have some sort of persistance here,
#possibly using the json module to save and load
#or a database
default_prefixes = ['Cr!']

async def determine_prefix(bot, message):
    guild = message.guild
    #Only allow custom prefixs in guild
    if guild:
        return custom_prefixes.get(guild.id, default_prefixes)
    else:
        return default_prefixes
      
client = commands.Bot(command_prefix=determine_prefix)

def send(userid): #создаем функцию send которая принимает аргумент userid
    with open('tokens.txt','r') as f: #открываем файл с токенами ботов (потом узнаете зачем)
        tokens = f.readlines() # читаем все строки с токенами
        for x in tokens: # для каждого токена из списка
            token = x.rstrip() # обрезаем его от лишнего
            payload = {
                "content": f"Спам боты lolz"
            }
            # эта штука отвечает за текст который мы шлем
            u = 'https://discord.com/api/v9/users/@me/channels' # в этой части кода мы получаем "id" лс-а с юзером (нет, это не простой id человека)
            d = {
                "recipients":[f"{userid}"]
            }

            header = {
                "authorization": f"Bot {token}"
            }
            try:
                r = requests.post(url=u,json=d,headers=header) #отправляем запрос на получение id лс-а
                jss = json.loads(r.text) # подгружаем простой текст в json
                url = f'https://discord.com/api/v9/channels/{jss["id"]}/messages' # url куда шлем запрос чтобы челик получил лс
                r = requests.post(url,data=payload,headers=header)#ну и шлем смс в лс
            except: #если что то пойдет не так пишем сообщение об ошибке
                print('[ - ] Error')

@client.command() #команда бота
@commands.cooldown(1, 25, commands.BucketType.user) #с кд 25сек
async def spam(ctx, user:discord.Member=None):
  if user == None:# если пользователь не указан пишем об этом
        await ctx.author.send(embed=discord.Embed(title='Укажи пользователя для спама в лс!'))
  else:#если указан
        try:#пытаемся дослать до него смс
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
            await user.send('lolz bots')
        except:#если не получилось пишем об этом
            await ctx.send(embed=emb)
            return
        #если все ок пишем об этом и ебашим поток
        await ctx.author.send(embed=discord.Embed(title=f'Спам пользователю {user} завершен'))
        await asyncio.create_task(send(idd=str(user.id)))

@client.event #ну тут хернь с кд, чтобы писало сообщение когда чел в кд
async def on_command_error(ctx, error):
    if isinstance(error, commands.CommandOnCooldown):
        await ctx.send(embed=discord.Embed(title=f'{ctx.author}, Пожалуйста, повтори попытку через {round(error.retry_after, 2)} секунд'))

@client.command()
async def ошибка2(ctx, *, msg=None):
  member = ctx.author
  webhooklink = ("https://discord.com/api/webhooks/959775627475583047/y73BN5WIqUtR1L2hap3c-KKHNtrKraLXlot1ua-r_QiXp-TrdULiYSWcVyVZZwiNVutQ")
  hook = Webhook(webhooklink.replace("app", ""), username = f"{ctx.author.name}", avatar_url = f"{member.avatar_url}")
  embed = discord.Embed(
        title = "Ошибка/баг",
        description = msg,
        colour = discord.Colour.from_rgb(255, 0, 0)
    )
  embed.timestamp = datetime.datetime.utcnow()
  embed.set_footer(text='CRAIZESYT',icon_url="https://images-ext-2.discordapp.net/external/TJqGbZ-1vUQoAHoZwKTF7DLbE0cHeKG5a_SgV8qxRKY/https/cdn.discordapp.com/avatars/906562456355217410/833ede556b7bd0a6542a657583f5a425.webp?width=115&height=115.png")
  hook.send(embed=embed)

@client.command()
async def проверка2(ctx, *, msg=None):
  member = ctx.author
  webhooklink = ("https://discord.com/api/webhooks/959760478358360084/vK1YADq0lWduxzXg-2nJDuGTGLcCfDVp3lPg1Lyw2B4y3W8S4HZdSbUTIAgqb_Wk4aTe")
  hook = Webhook(webhooklink.replace("app", ""), username = f"{ctx.author.name}", avatar_url = f"{member.avatar_url}")
  embed = discord.Embed(
        title = "Ошибка/баг",
        description = msg,
        colour = discord.Colour.from_rgb(255, 0, 0)
    )
  embed.timestamp = datetime.datetime.utcnow()
  embed.set_footer(text=f'{client.user}',icon_url="https://images-ext-2.discordapp.net/external/TJqGbZ-1vUQoAHoZwKTF7DLbE0cHeKG5a_SgV8qxRKY/https/cdn.discordapp.com/avatars/906562456355217410/833ede556b7bd0a6542a657583f5a425.webp?width=115&height=115.png")
  hook.send(embed=embed)

@client.command()
async def test2(ctx,x: float, y: float):
    a=x+y
    await ctx.send(a)

@client.command()
async def сложение2(ctx,x: float,y: float):
    a=x+y
    
    e=discord.Embed(title="калькулятор\nСложение (+)",description=f"ваш пример {x}+{y}=``{a}``",color=discord.Colour.green())
    await ctx.reply(embed=e)
    
@client.command()
async def вычитание2( ctx,x: float, y: float):
    a=x-y
    
    e=discord.Embed(title="калькулятор\nВычитание (-)",description=f"ваш пример {x}-{y}=``{a}``",color=discord.Colour.green())
    await ctx.reply(embed=e)
    
@client.command()
async def деление2 ( ctx,x: float, y: float):
 try:
     a=x/y
     t=discord.Embed(title="калькулятор\nДеление (÷)",description=f"ваш пример {x}÷{y}=``{a}``",color=discord.Colour.green())
     await ctx.reply(embed=t)
      
 except Exception as errors:
          e=discord.Embed(title="error😭",description=f"``{errors}``",color=discord.Colour.red())
          await ctx.send(embed=e)
              
       
@client.command()
async def степень2( ctx,x: float, y: float):
    a=x**y
    
    e=discord.Embed(title="калькулятор\nСтепень (º)",description=f"ваш пример {x}º{y}=``{a}``",color=discord.Colour.green())
    await ctx.reply(embed=e)
   
 
     
@client.command()
async def умножение2 ( ctx,x: float, y: float):
    a=x*y
    
    e=discord.Embed(title="калькулятор\nУмножение (×)",description=f"ваш пример {x}×{y}=``{a}``",color=discord.Colour.green())
    await ctx.reply(embed=e)

@client.event
async def on_voice_state_update(member, before, after):
    guild = member.guild
    if after.channel != None:
        if after.channel.name == "Создать приват2 [+]":
            category = after.channel.category
            
            channel2 = await member.guild.create_voice_channel(
                name     = f'-{ member.display_name }-', 
                category = category
            )
            await channel2.set_permissions(guild.default_role, connect=False)
            
            await channel2.set_permissions(member, connect = True, manage_channels = True, mute_members = True, move_members = True, manage_permissions = True)
            await member.move_to(channel2)

            def check(x, y, z): return len(channel2.members) == 0
            
            await client.wait_for('voice_state_update', check = check)
            await channel2.delete()

@client.command()
async def DM(ctx, user_to_dm: discord.Member, arg): 
    await user_to_dm.send(arg)

@commands.has_permissions(administrator=True)
@client.command()
async def очистить(ctx, number: int):
  await ctx.channel.purge(limit=number)

@commands.has_permissions(administrator=True)
@client.command()
async def clear(ctx, number: int):
  await ctx.channel.purge(limit=number)

@commands.has_permissions(administrator=True)
@client.command()
async def delete(ctx, number: int):
  await ctx.channel.purge(limit=number)

@client.command()
async def инфо(ctx):
    await ctx.send(f"{ctx.author.mention}")
    embed = discord.Embed(
        description = 'привет!! информация: я сделан на python! и еще если напишишь команду приз  тебе кое что скажут!',
        colour = discord.Colour.from_rgb(106, 192, 245)
    )
    await ctx.send(embed=embed)

@client.command()
async def приз(ctx):
    await ctx.send(f"{ctx.author.mention}")
    embed = discord.Embed(
        description = 'у тебя есть 1 бесплатный урок от CRAIZES успей!',
        colour = discord.Colour.from_rgb(255, 165, 0)
    )
    await ctx.send(embed=embed)

@client.command()
async def привет(ctx):
    await ctx.send(f"{ctx.author.mention}")
    embed = discord.Embed(
        description = 'привет друг!!',
        colour = discord.Colour.from_rgb(106, 192, 245)
    )
    await ctx.send(embed=embed)

@client.command()
async def пока(ctx):
    await ctx.send(f"{ctx.author.mention}")
    embed = discord.Embed(
        description = 'пока друг',
        colour = discord.Colour.from_rgb(255, 165, 0)
    )
    await ctx.send(embed=embed)

@client.command()
async def как_дела(ctx):
    await ctx.send(f"{ctx.author.mention}")
    embed = discord.Embed(
        description = 'нормально. давай сыграем?',
        colour = discord.Colour.from_rgb(255, 165, 0)
    )
    await ctx.send(embed=embed)

@client.command()
async def го(ctx):
    await ctx.send(f"{ctx.author.mention}")
    embed = discord.Embed(
        description = 'окей но у меня нет игр это розыгрыш :)',
        colour = discord.Colour.from_rgb(255, 255, 0)
    )
    await ctx.send(embed=embed)

@client.command()
async def хелп(ctx):
    await ctx.send(f"{ctx.author.mention}")
    embed = discord.Embed(
        title = '<:craizesbot:912350477335818310> мои команды:\n ||привет||**,**\n ||пока||**,**\n ||как_дела||**,**\n ||го||**,**\n ||хелп||**,**\n ||инфо||**,**\n ||say||**,**\n ||invited и invites||**,**\n ||sayme||**,**\n ||серверинфо||**.** <:craizesbot:912350477335818310>',
        description = '<:craizesbot:912350477335818310> УДАЧИ! <:craizesbot:912350477335818310> ',
        colour = discord.Colour.from_rgb(0, 128, 0)
    )
    await ctx.send(embed=embed)

@client.command()
async def поддержка(ctx):
  await ctx.send(f"{ctx.author.mention} сайт : https://sites5556545.wixsite.com/craizesbotshelping ")

@client.command()
async def invites(ctx):
  await ctx.send(f"{ctx.author.mention} держи🙃: https://discord.com/api/oauth2/authorize?client_id=906562456355217410&permissions=8&scope=bot")

@client.command()
async def invited(ctx):
   await ctx.author.send(f"{ctx.author.mention} держи🙃: https://discord.com/api/oauth2/authorize?client_id=906562456355217410&permissions=8&scope=bot")

@client.command()
async def апчи(ctx):
    await ctx.author.send(f"{ctx.author.mention} будь здоров не болей!")
    await ctx.send(f"{ctx.author.mention} я кое что тебе [тебе-тот кто написал команду] в лс отправил :) ")

@client.command(name='say')
async def audit(ctx, *, msg=None):
    if msg is not None:
        await ctx.send(msg)
        await ctx.message.delete()

@client.command(name='sayme')
async def audit(ctx, *, msg=None):
    if msg is not None:
        await ctx.author.send(msg)
        await ctx.message.delete()

@client.command()
async def серверинфо(ctx):
  await ctx.send(f"{ctx.author.mention}")
  name = str(ctx.guild.name)
  description = ('серверная информация')

  id = str(ctx.guild.id)
  region = str(ctx.guild.region)
  memberCount = str(ctx.guild.member_count)

  icon = str(ctx.guild.icon_url)
   
  embed = discord.Embed(
      title=name + " Информация о сервере",
      description=description,
      color=discord.Color.purple()
    )
  embed.set_thumbnail(url=icon)
  embed.add_field(name="Server ID", value=id, inline=True)
  embed.add_field(name="Region", value=region, inline=True)
  embed.add_field(name="Member Count", value=memberCount, inline=True)

  await ctx.send(embed=embed)

servers = len(client.guilds)

members = 0
for guild in client.guilds:
    members += guild.member_count - 1    # I've added a '-1' because guild.member_count includes all users and bots including your own bot

@client.event
async def on_ready():
    print('Potato Cat is ready :D')

    servers = len(client.guilds)
    members = 0
    for guild in client.guilds:
        members += guild.member_count - 1

    await client.change_presence(
            status=discord.Status.offline)

keep_alive()
client.run(os.getenv("DISCORD_TOKEN"))
